### ISSUE TITLE
バックエンドの環境構築

### ISSUE THREAD

**Issue by bonybody** [bonybody/omotadays-camera#4]
## バックエンドの環境
- ホストNodejsで動かす
- Nest.JS
- TypeScript
- ~~ORMはPrisma~~
  - ~~マイグレーションもPrismaでやってよさそう？~~
  - 外部キー多めでモデル定義するのが面倒
  - TypeORMでSQL生書きする
## DBの環境
- MySQL
- Docker Composeで動かす

## ToDo
- [x] Nest.JSのプロジェクトを`backend/`以下に作成
- [x] linter, formatterの設定を定める
- [x] `/`以下に`docker-compose.yml`を作成
- [x] `docker-compose.yml`にMySQLのための項目を作成
- [x] NestJSプロジェクト <=> MySQLで通信できるようにする
